server:
  port: 8080

spring:
  application:
    name: kuberdemo

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.dempapp: INFO
    org.springframework: INFO
